name: Generate Profile Readme

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 1 * * *" # every day at 1am
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.2.1
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt install bc jq
      - name: Run tests
        run: bats --tap test

  generate:
    name: Generate
    runs-on: ubuntu-latest
    env:
      WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
      LAFTEL_UID: ${{ secrets.LAFTEL_UID }}
      LAFTEL_TOKEN: ${{ secrets.LAFTEL_TOKEN }}
    needs: test
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt install figlet bc jq

      - name: Clean Readme
        run: echo "[![profile repository workflow](https://github.com/vbalien/vbalien/actions/workflows/push.yml/badge.svg)](https://github.com/vbalien/vbalien/actions/workflows/push.yml)" > Readme.md

      - name: Append figlet
        run: |
          echo "\`\`\`" >> Readme.md
          figlet -f big VBALIEN >> Readme.md
          echo "\`\`\`" >> Readme.md

      - name: Append badge
        run: |
          (
            echo "[![Telegram Badge](https://img.shields.io/badge/-Telegram-2CA5E0?logo=telegram)](https://t.me/vbalien)"
            echo "[![Keybase Badge](https://img.shields.io/badge/-Keybase-33A0FF?logo=keybase&logoColor=white)](https://keybase.io/vbalien)"
            echo "[![Keybase PGP](https://img.shields.io/keybase/pgp/vbalien)](http://sks.pod02.fleetstreetops.com/pks/lookup?search=0xE98CF73DE1E36F7D1B8A383AFD987F8DBE513071&fingerprint=on&op=index)"
            echo
          ) >> Readme.md

      - name: Append wakatime
        run: |
          echo "📊 Weekly development breakdown" >> Readme.md
          echo "\`\`\`" >> Readme.md
          curl -s -H "Authorization: Basic $(echo "$WAKATIME_API_KEY" | base64)" https://wakatime.com/api/v1/users/current/stats/last_7_days \
            | ./printWakatime.sh >> Readme.md
          echo "\`\`\`" >> Readme.md

      - name: Append laftel
        run: |
          echo "📺 Laftel 최근 본 애니" >> Readme.md
          echo "\`\`\`" >> Readme.md
          curl -s -H "laftel: TeJava" -H "authorization: Token $LAFTEL_TOKEN" https://laftel.net/api/v1.0/users/$LAFTEL_UID/playhistory_set/ \
            | ./printLaftel.sh >> Readme.md
          echo "\`\`\`" >> Readme.md

      - name: Git commit and push
        run: |
          git config user.email "gh-action-bot@alien.moe"
          git config user.name "Github Action Bot"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git checkout master
          git add Readme.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update"; git push origin master)
